### PR TITLE
Added four new spinners , Disk, DualBall , PivotBall and CubeGrid

### PR DESCRIPTION
**Pull request by YohannKovacs**
Added two new spinner components, DualBall spinner and Disk spinner .
spinners

These components accept two color parameters and one size parameter.
Updated README.md
Modified Gitignore to ignore Intellij Rider IDE cache

### CODE REVIEW

**Comment by ayodejii** [comment]
oh, good Paul, you are on a roll!

Thank you.

**Comment by YohannKovacs** [comment]
Created two more spinners- PivotBall and CubeGrid

Spinner

**Comment by YohannKovacs** [comment]
@ayodejii Any updates? Should i do any changes or is this okay to merge?

**Comment by ayodejii** [comment]
hi Paul, I 've been busy. Push all the new updates you have in this branch. I will test and merge when I'm free today.
Thank you.

**Pull request merged**
